from fastapi import APIRouter, HTTPException, Query
from typing import List, Dict, Any
from contabilidad.backend.models import InterpolationGroup, InterpolatedPayment, InterpolationGroupCreate, InterpolatedPaymentCreate
from contabilidad.backend.storage.variables_storage import InterpolationStorage

router = APIRouter()

# --- Groups ---

@router.get("/groups", response_model=List[InterpolationGroup])
def get_groups(type: str = Query('interpolated')):
    return InterpolationStorage.get_groups(type_filter=type)

@router.post("/groups", response_model=InterpolationGroup)
def create_group(group: InterpolationGroupCreate):
    # ID is generated by backend
    new_group = InterpolationStorage.create_group(group.name, group.description, group.type)
    return new_group

@router.put("/groups/{group_id}", response_model=InterpolationGroup)
def update_group(group_id: str, group: InterpolationGroupCreate):
    updated = InterpolationStorage.update_group(group_id, group.dict())
    if not updated:
        raise HTTPException(status_code=404, detail="Group not found")
    return updated

@router.delete("/groups/{group_id}")
def delete_group(group_id: str):
    success = InterpolationStorage.delete_group(group_id)
    if not success:
        raise HTTPException(status_code=404, detail="Group not found")
    return {"status": "success", "message": "Group deleted"}

# --- Payments ---

@router.get("/groups/{group_id}/payments", response_model=List[InterpolatedPayment])
def get_group_payments(group_id: str):
    payments = InterpolationStorage.get_payments(group_id)
    return payments

@router.post("/groups/{group_id}/payments", response_model=InterpolatedPayment)
def create_payment(group_id: str, payment: InterpolatedPaymentCreate):
    # Ensure group exists
    group = InterpolationStorage.get_group(group_id)
    if not group:
        raise HTTPException(status_code=404, detail="Group not found")
    
    new_payment = InterpolationStorage.create_payment(
        group_id=group_id,
        amount=payment.amount,
        start_date=payment.start_date,
        end_date=payment.end_date,
        note=payment.note
    )
    
    # ⚡ Invalidar solo transformaciones (los datos fuente no cambiaron)
    try:
        from contabilidad.backend.storage.data_pipeline import get_pipeline
        
        pipeline = get_pipeline()
        pipeline.invalidate_cache(scope='transformations')
    except Exception:
        pass  # No fallar si el pipeline no está disponible
    
    return new_payment

@router.put("/payments/{payment_id}", response_model=InterpolatedPayment)
def update_payment(payment_id: str, payment: InterpolatedPaymentCreate):
    updated = InterpolationStorage.update_payment(payment_id, payment.dict())
    if not updated:
        raise HTTPException(status_code=404, detail="Payment not found")
    
    # ⚡ Invalidar solo transformaciones
    try:
        from contabilidad.backend.storage.data_pipeline import get_pipeline
        
        pipeline = get_pipeline()
        pipeline.invalidate_cache(scope='transformations')
    except Exception:
        pass
    return_data = InterpolatedPayment(amount=updated['amount'], start_date=updated['start_date'], end_date=updated['end_date'], note=updated.get('note', ''), id=updated['id'], group_id=updated['group_id'])
    return return_data

@router.delete("/payments/{payment_id}")
def delete_payment(payment_id: str):
    success = InterpolationStorage.delete_payment(payment_id)
    if not success:
        raise HTTPException(status_code=404, detail="Payment not found")
    
    # ⚡ Invalidar solo transformaciones
    try:
        from contabilidad.backend.storage.data_pipeline import get_pipeline
        
        pipeline = get_pipeline()
        pipeline.invalidate_cache(scope='transformations')
    except Exception:
        pass
    
    return {"status": "success", "message": "Payment deleted"}

