from enum import Enum
from dataclasses import dataclass
from datetime import datetime

PATH_DATOS_ANTERIORES = "../datos_anteriores.csv" #todo unido
PATH_CUENTA_UNIDO = "../cuentas/unido.csv"
PATH_CUENTA_GUARDAR = "../cuentas/guardado/"

# PATH_DATOS_TARJETA = '../tarjeta/datos'

PATH_NOTION = "../notion/CuentasHasta7Agosto.csv"

CUENTAS_COLUMNAS = ["FECHA","SALDO","DESCRIPCION","DEBITO","CREDITO"]



PATH_DATA = "../data"
PATH_HISTORICO = PATH_DATA+"/historico"
PATH_UNIDO=PATH_DATA+"/unido"



PATH_ATIPICOS_DESCRIPCIONES = "../guardarCompleto/atipicos_descripciones.xlsx"

PATH_GUARDAR_ATIPICOS_HISTORICOS = PATH_HISTORICO+"/atipicos"
PATH_GUARDAR_COMPLETO_HISTORICOS = PATH_HISTORICO+"/completos"

PATH_ATIPICOS = PATH_UNIDO

PATH_BANCA_HISTORICO = PATH_HISTORICO+"/banca"

# PATH_BANCA_NUEVOS = PATH_BANCA_HISTORICO+"/nuevos"



PATH_BANCA_HISTORICO_COMPLETO = PATH_BANCA_HISTORICO+"/completos"

PATH_CUENTA_UNIDO  = PATH_UNIDO+"/cuentas.csv"




PATH_TARJETA_HISTORICO = PATH_HISTORICO+"/tarjeta"
PATH_TARJETAS_DATA_CRUDA = PATH_TARJETA_HISTORICO + "/nuevos"
PATH_TARJETAS_DATA = PATH_TARJETA_HISTORICO +  "/data"


PATH_DATA_ACTUAL_UNIDA = PATH_DATA+"/actual"

PATH_CUENTAS_ACTUAL_UNIDA = PATH_DATA_ACTUAL_UNIDA+"/cuentas.csv"
PATH_ATIPICOS_ACTUAL_UNIDA = PATH_DATA_ACTUAL_UNIDA+"/atipicos.xlsx"


PATH_PROCESADOS = PATH_DATA+"/procesada"
PATH_TARJETA_PROCESADA = PATH_PROCESADOS+"/tarjeta"


PATH_NUEVOS = PATH_DATA+"/nuevos"
PATH_BANCA_NUEVOS = PATH_NUEVOS+"/banca"
PATH_TARJETA_NUEVOS = PATH_NUEVOS+"/tarjeta"




MAPEO_COLUMNAS_DATOS_TARJETA = {
    "EMPRESA": "EMPRESA",
    "#TARJETA": "NUM_TARJETA",
    "FECHA_EMISION": "FECHA_EMISION",
    "FECHA_MAX_PAGO": "FECHA_MAX_PAGO",
}


COLUMNAS_DATOS_TARJETA_ORDENADAS =[]


PATH_TARJETA_HISTORICO_COMPLETO = PATH_TARJETA_HISTORICO+"/completos"
PATH_TARJETA_UNIDO = PATH_UNIDO+"/tarjeta.xlsx"

COLUMNAS_GUARDADAS = ["FECHA", "diff_TOTAL", "diff_tarjeta", "diff_saldo_sin_inversion","diff_notion", "DESCRIPCION","DESCRIPCION_NOTION","comentario","MADRE"]
COLUMNAS_GUARDAR_COMPLETO =['FECHA',"TOTAL", 'SALDO', 'TARJETA',"INVERSION","PAGOS_MENSUAL_MA INTER","NOTIONCUM","DESCRIPCION","MADRE"]
COLUMNAS_GUARDAR_CUENTAS = ['FECHA', 'SALDO', 'DESCRIPCION', "MONTO"]





PATH_COMPLETO = "guardarCompleto"
